name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt

      - name: Syntax check
        run: |
          python -m compileall app

      - name: Set GHCR image
        run: |
          IMAGE="ghcr.io/${{ github.repository_owner }}/secure-ai-devsecops-platform"
          IMAGE=$(echo "$IMAGE" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE=$IMAGE:${{ github.sha }}" >> "$GITHUB_ENV"

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          docker build \
            -t "$IMAGE" .

      - name: Push image
        run: |
          docker push "$IMAGE"

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Sign container image
        run: |
          cosign sign --yes "$IMAGE"

      - name: Verify image signature
        run: |
          cosign verify --certificate-identity-regexp="https://github.com/${{ github.repository_owner }}/secure-ai-devsecops-platform" --certificate-oidc-issuer="https://token.actions.githubusercontent.com" "$IMAGE"