name: Gitleaks Secret Scan

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  gitleaks:
    name: Secret Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check Gitleaks version
        run: |
          docker run --rm zricethezav/gitleaks:v8.18.4 version

      - name: Run Gitleaks
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/repo" \
            zricethezav/gitleaks:v8.18.4 \
            detect \
            --source=/repo \
            --report-format=json \
            --report-path=/repo/leaks.json \
            --redact \
            --exit-code=1

      - name: Upload Gitleaks report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: leaks.json

  trivy-fs:
    name: Trivy Filesystem Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Trivy filesystem scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          severity: HIGH,CRITICAL
          exit-code: 1

  trivy-image:
    name: Trivy Container Image Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build image
        run: |
          docker build \
            -t secure-ai-devsecops-platform:${{ github.sha }} .

      - name: Scan image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: secure-ai-devsecops-platform:${{ github.sha }}
          severity: HIGH,CRITICAL
          exit-code: 1
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'        
